# Generated by Django 2.2.3 on 2019-10-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suser', models.CharField(max_length=50)),
                ('semail', models.CharField(max_length=50)),
                ('spassword', models.CharField(max_length=50)),
            ],
        ),
    ]
